[workspace]
members = [
    "builder",
    "kernel",
    "driver/acpid",
    "driver/pcid",
    "driver/nvmed",
    "driver/fsmd",
    "kernel/crates/*",
]
resolver = "2"
default-members = ["builder"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 0
panic = "abort"
strip = true
